In [0]:
from sklearn.datasets import load_boston
from sklearn.preprocessing import MinMaxScaler

In [0]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression

In [0]:
boston_data =load_boston()

In [0]:
X = boston_data.data

In [0]:
y= boston_data.target

In [7]:
X.mean(axis=0)  #All rows added up

array([3.61352356e+00, 1.13636364e+01, 1.11367787e+01, 6.91699605e-02,
       5.54695059e-01, 6.28463439e+00, 6.85749012e+01, 3.79504269e+00,
       9.54940711e+00, 4.08237154e+02, 1.84555336e+01, 3.56674032e+02,
       1.26530632e+01])

In [8]:
X.shape

(506, 13)

In [0]:
scaler = MinMaxScaler()

In [0]:
model =LinearRegression()

In [0]:
pipeline = Pipeline([("Scaling Model", scaler),
                         ("linear_regression", model)])
    #pipeline.fit(X[:, np.newaxis], y)


In [12]:
print(pipeline)

Pipeline(memory=None,
         steps=[('Scaling Model',
                 MinMaxScaler(copy=True, feature_range=(0, 1))),
                ('linear_regression',
                 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                                  normalize=False))],
         verbose=False)


In [13]:
pipeline.fit(X,y)

Pipeline(memory=None,
         steps=[('Scaling Model',
                 MinMaxScaler(copy=True, feature_range=(0, 1))),
                ('linear_regression',
                 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                                  normalize=False))],
         verbose=False)

In [14]:
pipeline.steps[0][1].data_max_

array([ 88.9762, 100.    ,  27.74  ,   1.    ,   0.871 ,   8.78  ,
       100.    ,  12.1265,  24.    , 711.    ,  22.    , 396.9   ,
        37.97  ])

In [15]:
pipeline.steps[1][1].coef_

array([ -9.60975755,   4.64204584,   0.56083933,   2.68673382,
        -8.63457306,  19.88368651,   0.06721501, -16.22666104,
         7.03913802,  -6.46332721,  -8.95582398,   3.69282735,
       -19.01724361])

In [16]:
pipeline.steps[1][1].intercept_

26.6202675846878

In [17]:
pipeline.predict(X)

array([30.00384338, 25.02556238, 30.56759672, 28.60703649, 27.94352423,
       25.25628446, 23.00180827, 19.53598843, 11.52363685, 18.92026211,
       18.99949651, 21.58679568, 20.90652153, 19.55290281, 19.28348205,
       19.29748321, 20.52750979, 16.91140135, 16.17801106, 18.40613603,
       12.52385753, 17.67103669, 15.83288129, 13.80628535, 15.67833832,
       13.38668561, 15.46397655, 14.70847428, 19.54737285, 20.8764282 ,
       11.45511759, 18.05923295,  8.81105736, 14.28275814, 13.70675891,
       23.81463526, 22.34193708, 23.10891142, 22.91502612, 31.35762569,
       34.21510225, 28.02056414, 25.20386628, 24.60979273, 22.94149176,
       22.09669817, 20.42320032, 18.03655088,  9.10655377, 17.20607751,
       21.28152535, 23.97222285, 27.6558508 , 24.04901809, 15.3618477 ,
       31.15264947, 24.85686978, 33.10919806, 21.77537987, 21.08493555,
       17.8725804 , 18.51110208, 23.98742856, 22.55408869, 23.37308644,
       30.36148358, 25.53056512, 21.11338564, 17.42153786, 20.78

In [0]:
Pipeline?

In [0]:
from joblib import dump, load

In [20]:
dump(model,"trained_model.gzpipe

['trained_model.gz']

In [21]:
dump(pipeline,"pipeline_model.gz")

['pipeline_model.gz']

In [0]:
pipeline =load("pipeline_model.gz")

In [23]:
print(pipeline) 

Pipeline(memory=None,
         steps=[('Scaling Model',
                 MinMaxScaler(copy=True, feature_range=(0, 1))),
                ('linear_regression',
                 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                                  normalize=False))],
         verbose=False)


In [24]:
pipeline.predict(X)

array([30.00384338, 25.02556238, 30.56759672, 28.60703649, 27.94352423,
       25.25628446, 23.00180827, 19.53598843, 11.52363685, 18.92026211,
       18.99949651, 21.58679568, 20.90652153, 19.55290281, 19.28348205,
       19.29748321, 20.52750979, 16.91140135, 16.17801106, 18.40613603,
       12.52385753, 17.67103669, 15.83288129, 13.80628535, 15.67833832,
       13.38668561, 15.46397655, 14.70847428, 19.54737285, 20.8764282 ,
       11.45511759, 18.05923295,  8.81105736, 14.28275814, 13.70675891,
       23.81463526, 22.34193708, 23.10891142, 22.91502612, 31.35762569,
       34.21510225, 28.02056414, 25.20386628, 24.60979273, 22.94149176,
       22.09669817, 20.42320032, 18.03655088,  9.10655377, 17.20607751,
       21.28152535, 23.97222285, 27.6558508 , 24.04901809, 15.3618477 ,
       31.15264947, 24.85686978, 33.10919806, 21.77537987, 21.08493555,
       17.8725804 , 18.51110208, 23.98742856, 22.55408869, 23.37308644,
       30.36148358, 25.53056512, 21.11338564, 17.42153786, 20.78

In [1]:
! pip install cookiecutter

In [ ]:
!cookiecutter https://github.com/drivendata/cookiecutter-data-science